CREATE DATABASE IF NOT EXISTS coffees;

USE coffees;

CREATE TABLE IF NOT EXISTS coffee (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (128) NOT NULL,
    version INTEGER NOT NULL
)  ENGINE=INNODB;
